import subprocess
import time

# List of Surah Slugs (simplified example, you can expand this)
# A full list can be generated by scraping the homepage index
SURAH_LIST = [
    (1, "al-fatihah"),
    (2, "al-baqarah"),
    (3, "ali-imran"),
    (4, "an-nisa"),
    (5, "al-maidah"),
    # ... add more as needed
]

def run_part(surah_num, surah_slug):
    print(f"--- Starting Part: Surah {surah_num} ({surah_slug}) ---")
    cmd = [
        "python", "OpenBayanBackend/notebooks/flows/scrape_tafsirweb.py"
    ]
    # Note: The script I wrote defaults to Al-Fatihah if run as __main__, 
    # but for a production batch run, we would modify the script 
    # to accept CLI arguments or use a Prefect deployment.
    
    # For now, I'll modify the scraper slightly to handle CLI args 
    # OR just demonstrate how to call the function directly if imported.
    pass

if __name__ == "__main__":
    print("To run in parts, use the Prefect CLI or call the flow function.")
    print("Example: prefect deployment run 'TafsirWeb Scraper (Modular)/my-run' --param surah_num=1 --param surah_slug='al-fatihah'")
